name: Code Feature Flow
concurrency: ${{ github.event.repository.name }}-feature
on:
    push:
        branches:
            - 'feature/**'
            - 'fix/**'
            - 'feat:/**'
jobs:
    build_and_test:
        runs-on: ubuntu-latest
        name: Build and test
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install and Build
              uses: ./.github/actions/build

            - name: Build tests
              uses: ./.github/actions/quality

    create_pull_request:
        runs-on: ubuntu-latest
        name: Dev Pull Request
        needs: build_and_test
        steps:
            - uses: actions/checkout@v2

            - name: Make changes to pull request
              run: date +%s > report.txt

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: merging feature into dev
                  author: ${{ github.actor }} <${{ github.actor }}>
                  signoff: false
                  branch: ${{ github.ref }}
                  base: dev
                  title: 'Merge feature into dev branch'
                  body: |
                      Update report
                      desplegando features nuevos en dev. :heart:
                  labels: |
                      report
                      automated pr
                  team-reviewers: |
                    legalizacion-reviewers
                    checkpoint-review
